# Dockerfile
FROM node:22-alpine

# Set working directory inside the container
WORKDIR /app

# Copy all files from host to container
COPY . .

# Install dependencies
RUN npm install
RUN npm audit fix

# Start app in dev mode
CMD ["npm", "run", "start:dev"]